# Generated by Django 5.1.15 on 2026-05-28 08:06

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество на складе')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
            },
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вид запчасти')),
            ],
            options={
                'verbose_name': 'Вид запчасти',
                'verbose_name_plural': 'Виды запчастей',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(validators=[core.models.validate_age_18], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='master',
            name='birth_date',
            field=models.DateField(validators=[core.models.validate_age_18], verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='order',
            name='parts',
            field=models.ManyToManyField(blank=True, to='core.part', verbose_name='Запчасти'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parttype', verbose_name='Вид'),
        ),
    ]
