# Generated by Django 5.1.15 on 2026-05-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_part_parttype_alter_client_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, upload_to='masters/', verbose_name='Фото'),
        ),
    ]
